export const TOPIC_LEADS: Record<string, string> = {
  hope: 'The Bible speaks of hope as a confident waiting on God, not a vague wish. These King James verses gather trust, patience, and expectation for hard seasons.',
  comfort: 'When trouble comes, Scripture points to God as the one who comforts the downcast. Read KJV passages on peace, rest, and courage in fear.',
  love: 'Love is the great commandment and the character of God in the King James Bible. These verses speak of charity, belovedness, and lovingkindness.',
  faith: 'Faith in the King James Bible is believing God and taking him at his word. These excerpts highlight trust, faithfulness, and belief that acts.',
  strength: 'Believers are told to be strong in the Lord, not merely in themselves. These KJV verses speak of courage, might, and God who strengtheneth.',
  peace: 'Biblical peace is more than the absence of conflict; it is rest in God. These King James passages address quietness, calm, and a heart that is not troubled.',
  forgiveness: 'The Bible joins God’s mercy with the call to forgive others. These KJV verses speak of pardon, compassion, and a clean heart.',
  wisdom: 'Wisdom in Scripture begins with the fear of the Lord and shows itself in understanding. These King James excerpts commend knowledge that lives well.',
  fear: 'The Bible both names human fear and calls people not to be afraid. These KJV verses offer courage when we tremble or are dismayed.',
  joy: 'Joy in the King James Bible is gladness rooted in God, even in trial. These verses invite rejoicing and a glad heart.',
  prayer: 'Prayer in Scripture is asking, seeking, and knocking with confidence that God hears. These King James verses teach how to pray and why it matters.',
  anxiety: 'Worry is met in the Bible with trust, prayer, and the care of God. These KJV verses speak to anxious thoughts and a guarded heart.',
  healing: 'The Bible records God’s power to heal and the hope of restoration. These King James passages comfort the sick and those who wait for mercy.',
  salvation: 'Salvation in the King James Bible is deliverance by God’s grace through faith. These verses name sin, the Saviour, and the gift of eternal life.',
  children: 'Scripture treats children as a heritage and calls parents to teach them diligently. These KJV verses speak of sons, daughters, and the next generation.',
  marriage: 'The Bible honors marriage as a covenant of love, faithfulness, and leaving and cleaving. These King James excerpts guide husbands and wives.',
  money: 'Scripture warns against greed and commends generous, honest dealing. These KJV verses speak of treasure, giving, and contentment.',
  patience: 'Patience in the King James Bible is longsuffering while we wait on God. These verses encourage endurance when answers are slow.',
  humility: 'God resists the proud and gives grace to the humble. These KJV passages call for a lowly mind and a servant heart.',
  thanksgiving: 'Thanksgiving is the Bible’s answer to both plenty and want. These King James verses teach gratitude, praise, and a thankful heart.',
  sorrow: 'The Scriptures do not deny grief; they meet it with comfort and hope. These KJV verses speak to tears, mourning, and the God of all consolation.',
  anger: 'The Bible warns that wrath works not the righteousness of God. These King James verses teach slow anger, self-control, and peacemaking.',
  guidance: 'God promises to lead those who trust him, by his word and his Spirit. These KJV verses seek direction, light for the path, and a willing heart.',
  protection: 'Believers are invited to dwell in the secret place of the Most High. These King James passages speak of refuge, covering, and the Lord as a shield.',
};

export const NEW_TOPIC_IDS = [
  'prayer',
  'anxiety',
  'healing',
  'salvation',
  'children',
  'marriage',
  'money',
  'patience',
  'humility',
  'thanksgiving',
  'sorrow',
  'anger',
  'guidance',
  'protection',
] as const;
